name: Build code

on: push

jobs:
  build-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: bun run
      - name: Build
        run: bun run build
      - name: Build SWC
        run: bun run build:swc